### ISSUE TITLE
只要voc的？训练是07+12？测试是07的测试？请问coco的效果呢？

### ISSUE THREAD

**Issue by henbucuoshanghai** [devinhee/tf_yolov4#1]

**Comment by devinhee** [comment]
Train and Val sets: VOCtrainval_11-May-2012; Test set: VOCtest_06-Nov-2007. 
I‘m sorry. The evaluation results on COCO datasets may be conducted  in next few month, maybe not, it depends.

**Comment by henbucuoshanghai** [comment]
how long it takes to train the yolo4 with coco2014,with two 2080 GPUS?  may be a week?

**Comment by devinhee** [comment]
> how long it takes to train the yolo4 with coco2014,with two 2080 GPUS? may be a week?

One week is enough, you need choose suitable batch size.
